services:
  stocktradehistory:
    image: chenpinetree/stocktradehistory:latest
    container_name: stocktradehistory
    ports:
      - "3737:3737"
    environment:
      - PORT=3737
      - APP_DATA_DIR=/app/data
    volumes:
      - /volume1/docker/stocktradehistory/data:/app/data
    restart: unless-stopped
